project:
  type: website
  output-dir: docs
  
website:
  title: "Emily Mensch !"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/MenschEmily
      - icon: github
        href: https://github.com/emily-mensch
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Emily Mensch"

format:
  html:
    theme: darkly
    toc: true

editor: source

