project:
  type: website
  output-dir: docs
  
website:
  title: "Emily Mensch !"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research
      - href: CV.qmd
        text: CV
      - href: media.qmd
        text: Media
    tools:
      - icon: twitter
        href: https://twitter.com/MenschEmily
      - icon: github
        href: https://github.com/emily-mensch


format:
  html:
    theme: styles.scss
    mainfont: 'Jost'
    toc: true

editor: source

