---
pagetitle: Media
title: Media
---
<style type="text/css">
h1.title {
  text-align: center;
}
</style>

***

### Articles  
* UC Davis College of Agricultural and Environmental Sciences, [Birds and Fish in Flooded Rice Fields: Promoting Biodiversity and Climate Protection](https://caes.ucdavis.edu/news/birds-and-fish-flooded-rice-fields-promoting-biodiversity-and-climate-protection)

* California Water Blog, ["Got Blood? Unmasking a vampire fish"](https://californiawaterblog.com/2024/10/27/got-blood-unmasking-a-vampire-fish/)

* Spotlight Magazine, ["Sea Lamprey: Monsters or Misunderstood?"](https://spotlight-msu.medium.com/sea-lamprey-monsters-or-misunderstood-b8214a070de3)

### Videos
* UC Davis College of Agticultural and Environmental Sciences, [Fish in the Fields: UC Davis's Bold Approach to Sustainable Farming](https://www.youtube.com/watch?v=z642dQCTa3c)

### Podcasts 
* The Sci-Files – Impact 89 FM, [Novel Invasive Species Management of the Sea Lamprey](https://impact89fm.org/91837/podcasts/the-sci-files-11-1-2020-emily-mensch-novel-invasive-species-management-of-the-sea-lamprey/) 

* Women and Minorities in the Physical Sciences (WaMPS), [Journeys of Scientists](https://www.everand.com/podcast/591512260/Episode-17-Emily-Mensch)  

### Relevant student run publications! 
I love student led publications, and think they are a wonderful way to get a taste of a breadth of research - and they also help place you in the heart of graduate student communities. Graduate students are passionate, smart, caring, and creative and their words, thoughts, poems, pictures (and more!) deserve to be seen. Below, check out the UC Davis Ecology Graduate Group's student run magazine, the Aggie Brickyard, where I was once an editor and content creator, and Michigan State University's Fisheries and Wildlife graduate study run magazine, the Spotlight, where I formerly was an editor/designer/writer: 

* [The Aggie Brickyard!](https://aggiebrickyard.github.io/)

* [MSU FW's Spotlight Magazine](https://spotlight-msu.medium.com/) 
